import turtle as t
screen=t.Screen()
screen.setup(1000,800)
t.speed(0)
def tri(a,b,c,color):
    t.pu()
    t.goto(a[0],a[1])
    t.pd()
    t.fillcolor(color)
    t.begin_fill()
    for point in [a,b,c,a]:
        t.goto(point[0],point[1])
    t.end_fill()
def square(x,y,a,angle,color):
    t.pu()
    t.goto(x,y)
    t.setheading(angle)
    t.pd()
    t.fillcolor(color)
    t.begin_fill()
    for point in range(4):
        t.right(90)
        t.fd(a)
    t.end_fill()
def parallelogram (x,y,a,b,color):
    t.up()
    t.goto(x,y)
    t.pd()
    t.setheading(0)
    t.fillcolor(color)
    t.begin_fill()
    t.fd(a)
    t.left(45)
    t.fd(b)
    t.left(135)
    t.fd(a)
    t.left(45)
    t.fd(b)
    t.end_fill()
def center_cube():
    tri((0,0),(0,100),(50,50),'yellow')
    tri((0,100),(100,100),(50,50),'red')
    tri((100,100),(100,50),(75,75),'purple')
    tri((100,0),(100,50),(50,0),'lightblue')
    tri((50,50),(75,25),(25,25),'pink')
    square(75,75,35,45,'orange')
    rhomb(0,0,50,35,'green')
center_cube()
t.done()